* My Emacs config

* Package management

** Sources

#+BEGIN_SRC emacs-lisp
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
#+END_SRC

** use-package

The package manager I use.

#+BEGIN_SRC emacs-lisp
(require 'use-package)
(setq use-package-always-ensure t)
(setq inhibit-startup-message t)
(setq package-install-upgrade-built-in t)
#+END_SRC

** Automatic updates

#+BEGIN_SRC emacs-lisp
(use-package auto-package-update
  :custom
  (auto-package-update-prompt-before-update t)
  (auto-package-update-hide-results t)
  (auto-package-update-delete-old-versions t)
  (auto-package-update-interval 7) ; check every 7 days
  :config
  (auto-package-update-maybe))
#+END_SRC

* UI

** Font

Use the Monocraft Font.

#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default nil :font "Monocraft")
#+END_SRC

** Theme

Use the gruvbox color palette.

#+BEGIN_SRC emacs-lisp
(use-package gruvbox-theme :config (load-theme 'gruvbox-dark-medium t))
#+END_SRC

** Transparent background

#+BEGIN_SRC emacs-lisp
(set-frame-parameter nil 'alpha-background 80)
(add-to-list 'default-frame-alist '(alpha-background . 80))
#+END_SRC

** disable stupid stuff

#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(menu-bar-mode -1)
#+END_SRC

** Relative line numbers

#+BEGIN_SRC emacs-lisp
(setq-default display-line-numbers-type 'relative) 
(global-display-line-numbers-mode 1)
#+END_SRC

Exculde some modes from having relative line numbers.

#+BEGIN_SRC emacs-lisp
(dolist (mode-hook '(vterm-mode-hook eshell-mode-hook))
  (add-hook mode-hook (lambda () (display-line-numbers-mode 0))))
#+END_SRC

** Rainbow delimiters

#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters
             :hook (prog-mode . rainbow-delimiters-mode))
#+END_SRC

** Doom modeline

#+BEGIN_SRC emacs-lisp
(use-package doom-modeline
             :init (setq doom-modeline-icon t)
             :config (doom-modeline-mode 1))
#+END_SRC

** icons

#+BEGIN_SRC emacs-lisp
(use-package nerd-icons)
#+END_SRC

** Color column

#+BEGIN_SRC emacs-lisp
  (setq-default fill-column 80)
  (add-hook 'prog-mode-hook #'display-fill-column-indicator-mode)
#+END_SRC

* QOL

** Backup file dir

#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist `(("." . ,(expand-file-name "backup/" user-emacs-directory))))
(make-directory (expand-file-name "backup/" user-emacs-directory) t)
#+END_SRC

** Commenting

#+BEGIN_SRC emacs-lisp
  (use-package evil-nerd-commenter
    :after evil
    :config
    (define-key evil-normal-state-map (kbd "gc") 'evilnc-comment-or-uncomment-lines)
    (define-key evil-visual-state-map (kbd "gc") 'evilnc-comment-or-uncomment-lines)
    )
#+END_SRC

** Indentation

*** Spaces instead of tabs

#+BEGIN_SRC emacs-lisp
  (setq tab-width 2)
  (setq evil-shift-width 2)
  (setq indent-tabs-mode nil)
#+END_SRC

*** Automatic indentation

#+BEGIN_SRC emacs-lisp
  (electric-indent-mode 1)
#+END_SRC

* Keybinds and other

** Make ESC quit prompts

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+END_SRC

** which-key

Show available keycombos on keypress.

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :init (which-key-mode)
    :diminish which-key-mode
    :config (setq which-key-idle-delay 0.3))
#+END_SRC

** Evil mode (vim motions)

#+BEGIN_SRC emacs-lisp
  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    (setq evil-undo-system 'undo-tree)
    (setq evil-want-fine-undo 'fine)
    :config
    (evil-mode 1)

  					; visual move as standard move
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)
    )
#+END_SRC

And enable undo in non buffer files (?)

#+BEGIN_SRC emacs-lisp
    (use-package undo-tree
      :after evil
      :init
      (global-undo-tree-mode)
      (add-hook 'evil-local-mode-hook 'turn-on-undo-tree-mode)
      :config
      (make-directory (expand-file-name "undo/" user-emacs-directory) t)
      (setq undo-tree-history-directory-alist
          `(("." . ,(expand-file-name "undo/" user-emacs-directory))))
      )
#+END_SRC

Add some more evil keybindings.

#+BEGIN_SRC emacs-lisp
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+END_SRC

** general

Here are all keybinds starting with space

#+BEGIN_SRC emacs-lisp
  (use-package general
    :config
    (general-evil-setup t)

    (general-create-definer dtiderko/leader-keys
      :keymaps '(normal visual emacs)
      :prefix "SPC")
    )
#+END_SRC

* M-x search

I dont really get this stuff but as far as i know everything under this chapter
serves to make M-x as usable as possible.

** ivy

#+BEGIN_SRC emacs-lisp
  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill)
           )
    :config
    (ivy-mode 1))
#+END_SRC

And an extension to show more information.

#+BEGIN_SRC emacs-lisp
  (use-package ivy-rich
    :after counsel
    :init
    (ivy-rich-mode 1))
#+END_SRC

** counsel

#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :bind (("M-x" . counsel-M-x)
           ("C-x b" . counsel-ibuffer)
           ("C-x C-f" . counsel-find-file)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :config
    (setq ivy-initial-inputs-alist nil)
    (counsel-mode 1))
#+END_SRC

** prescient

Improve order of M-x entries.

#+BEGIN_SRC emacs-lisp
  (use-package ivy-prescient
    :after counsel
    :custom
    (ivy-prescient-enable-filtering nil)
    :config
    (prescient-persist-mode 1)
    (ivy-prescient-mode 1))
#+END_SRC

** helpful

Add helpful information to Emacs' describe- command buffers.

#+BEGIN_SRC emacs-lisp
  (use-package helpful
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))
#+END_SRC

* File management

** grease

#+BEGIN_SRC emacs-lisp
  (use-package grease
    :load-path "~/.emacs.d/lisp/grease.el"
    :commands (grease-open grease-toggle grease-here)
  )

  (dtiderko/leader-keys "pv" '(grease-toggle :which-key "Open grease"))
#+END_SRC

* Development environments

** projectile

Support for project management.

#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :init
    (setq projectile-project-search-path '(
					   ("~/" . 1)
					   ("~/Projects" . 2)
					   ))
    :config
    (setq projectile-enable-caching t)
    (global-set-key (kbd "C-c p") 'projectile-command-map)
    (projectile-mode +1)
    )

  (dtiderko/leader-keys
    "SPC" '(projectile-find-file :which-key "Find file in project")
    "g" '(projectile-ripgrep :which-key "Grep the project")
    )
#+END_SRC

And auto discover all available projects.

#+BEGIN_SRC emacs-lisp
(projectile-discover-projects-in-search-path)
#+END_SRC

Extension to intergrate with counsel.

#+BEGIN_SRC emacs-lisp
(use-package counsel-projectile
  :after projectile
  :config (counsel-projectile-mode))
#+END_SRC

** envrc

Enter devenv on project enter.

#+BEGIN_SRC emacs-lisp
(use-package envrc
  :hook (after-init . envrc-global-mode))
(with-eval-after-load 'envrc
  (define-key envrc-mode-map (kbd "C-c e") 'envrc-command-map))
#+END_SRC

** LSP

*** install lsp

#+BEGIN_SRC emacs-lisp
    (use-package lsp-mode
      :init
      ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
      (setq lsp-keymap-prefix "C-c l")
      :hook (
             (lsp-mode . lsp-enable-which-key-integration)

             (c++-mode . lsp-deferred)
             (c-mode . lsp-deferred)
             (cmake-mode . lsp-deferred)
             (css-mode . lsp-deferred)
             (haskell-mode . lsp-deferred)
             (html-mode . lsp-deferred)
             (js-mode . lsp-deferred)
             (json-mode . lsp-deferred)
             (lua-mode . lsp-deferred)
             (markdown-mode . lsp-deferred)
             (nix-mode . lsp-deferred)
             (python-mode . lsp-deferred)
             (rust-mode . lsp-deferred)
             (sh-mode . lsp-deferred)
             (yaml-mode . lsp-deferred)
             (zig-mode . lsp-deferred)
             (glsl-mode . lsp-deferred)
            )
      :commands (lsp lsp-deferred))

    (use-package lsp-ui
      :commands lsp-ui-mode
      :custom
      (lsp-ui-doc-position 'at-point))
    (use-package lsp-ivy :commands lsp-ivy-workspace-symbol)

    ; performance tuning
    (setq gc-cons-threshold 100000000)
    (setq read-process-output-max (* 1024 1024)) ;; 1mb
#+END_SRC

*** auto formatting

#+BEGIN_SRC emacs-lisp
(use-package apheleia :config (apheleia-global-mode +1))
#+END_SRC

*** keybinds

#+BEGIN_SRC emacs-lisp
  (with-eval-after-load 'evil
    (evil-define-key 'normal lsp-mode-map
      ; help
      (kbd "K")  'lsp-ui-doc-glance
      (kbd "gd") 'lsp-find-definition
      (kbd "gD") 'lsp-find-declaration
      (kbd "gi") 'lsp-find-implementation
      (kbd "go") 'lsp-find-type-definition
      (kbd "gr") 'lsp-find-references
      (kbd "gs") 'lsp-signature-activate

      ; errors
      (kbd "gl") 'lsp-ui-flycheck-list)) ; or 'flymake-show-buffer-diagnostics

  ; actions
  (dtiderko/leader-keys
    "rn" '(lsp-rename :which-key "Rename symbol")
    "a"  '(lsp-execute-code-action :which-key "Code action"))
#+END_SRC

* Git

** Magit

Interface for git

#+BEGIN_SRC emacs-lisp
(use-package transient)
(use-package magit :after transient)
(dtiderko/leader-keys "G" '(magit-status :which-key "Open Magit"))
#+END_SRC

** Git Gutter

Actually good guide here: https://ianyepan.github.io/posts/emacs-git-gutter/

Show which lines are new/deleted/modified

#+BEGIN_SRC emacs-lisp
  (use-package git-gutter
    :hook (prog-mode . git-gutter-mode)
    :config
    (setq git-gutter:update-interval 0.02))
#+END_SRC

And modify the Bitmap for appearance

#+BEGIN_SRC emacs-lisp
  (use-package git-gutter-fringe
    :config
    (define-fringe-bitmap 'git-gutter-fr:added [224] nil nil '(center repeated))
    (define-fringe-bitmap 'git-gutter-fr:modified [224] nil nil '(center repeated))
    (define-fringe-bitmap 'git-gutter-fr:deleted [128 192 224 240] nil nil 'bottom)
    )
#+END_SRC

* Terminal

This terminal needs to compile a native library. Therefore, make sure to install all required libraries.

#+BEGIN_SRC emacs-lisp
  (use-package vterm
    :commands vterm
    :config
    (setq vterm-shell "bash")
  )
#+END_SRC

And add a keybind to open a new unique terminal.
  
#+BEGIN_SRC emacs-lisp
  (defun unique-vterm ()
    (interactive)
    (vterm)
    (rename-uniquely)
    )
  (dtiderko/leader-keys "t" '(unique-vterm :which-key "Open Terminal"))
#+END_SRC
