* My Emacs config

* Package management

** Sources

#+BEGIN_SRC emacs-lisp
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")
                         ))
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
#+END_SRC

** use-package

The package manager I use.

#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)
(setq inhibit-startup-message t)
#+END_SRC

** Automatic updates

#+BEGIN_SRC emacs-lisp
(use-package auto-package-update
  :custom
  (auto-package-update-prompt-before-update t)
  (auto-package-update-hide-results t)
  :config
  (auto-package-update-maybe)
  (auto-package-update-at-time "09:00"))
#+END_SRC

* UI

** Font

Use the JetBrains Mono Nerd Font.

#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default nil :font "JetBrains Mono Nerd Font")
#+END_SRC

** Theme

Use the gruvbox color palette.

#+BEGIN_SRC emacs-lisp
(use-package gruvbox-theme)
(load-theme 'gruvbox-dark-medium t)
#+END_SRC

** Transparent background

#+BEGIN_SRC emacs-lisp
  (set-frame-parameter nil 'alpha-background 70)
  (add-to-list 'default-frame-alist '(alpha-background . 70))
#+END_SRC

** disable stupid stuff

#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(menu-bar-mode -1)
#+END_SRC

** Relative line numbers

#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type 'relative) 
(global-display-line-numbers-mode)
#+END_SRC

Exculde some modes from having relative line numbers.

#+BEGIN_SRC emacs-lisp
(dolist (mode '(vterm-mode-hook
                 eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+END_SRC

** Rainbow delimiters

#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters
             :hook (prog-mode . rainbow-delimiters-mode))
#+END_SRC

** Doom modeline

#+BEGIN_SRC emacs-lisp
(use-package doom-modeline
             :init
             (setq doom-modeline-icon t)
             (doom-modeline-mode 1)
             )
#+END_SRC

** icons

#+BEGIN_SRC emacs-lisp
(use-package nerd-icons)
#+END_SRC

** Color column

#+BEGIN_SRC emacs-lisp
  (setq-default fill-column 80)
  (add-hook 'prog-mode-hook #'display-fill-column-indicator-mode)
#+END_SRC

* QOL

** Autosave file dir

First ensure the autosave dir exists

#+BEGIN_SRC emacs-lisp
  (unless (file-exists-p "~/.emacs.d/autosave")
    (make-directory "~/.emacs.d/autosave")
  )
#+END_SRC

Then make sure autosaves get stored there

#+BEGIN_SRC emacs-lisp
  ;(setq auto-save-list-file-prefix "~/.emacs.d/autosave/")
(setq auto-save-file-name-transforms
      '((".*" "~/.emacs.d/autosave/" t)))
#+END_SRC

** Backup file dir

#+BEGIN_SRC emacs-lisp
  (unless (file-exists-p "~/.emacs.d/backup")
    (make-directory "~/.emacs.d/backup")
  )
(setq backup-directory-alist `(("." . "~/.emacs.d/backup/")))
#+END_SRC

** Commenting

#+BEGIN_SRC emacs-lisp
  (use-package evil-nerd-commenter
    :after evil
    :config
    (define-key evil-normal-state-map (kbd "gc") 'evilnc-comment-or-uncomment-lines)
    (define-key evil-visual-state-map (kbd "gc") 'evilnc-comment-or-uncomment-lines)
    )
#+END_SRC

** Indentation

*** Spaces instead of tabs

#+BEGIN_SRC emacs-lisp
  (setq tab-width 2)
  (setq evil-shift-width 2)
  (setq indent-tabs-mode nil)
#+END_SRC

*** Automatic indentation

#+BEGIN_SRC emacs-lisp
  (electric-indent-mode 1)
#+END_SRC

* Keybinds and other

** Make ESC quit prompts

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+END_SRC

** which-key

Show available keycombos on keypress.

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :init (which-key-mode)
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 0.3))
#+END_SRC

** Evil mode (vim motions)

#+BEGIN_SRC emacs-lisp
  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    (setq evil-undo-system 'undo-tree)
    (setq evil-want-fine-undo 'fine)
    :config
    (evil-mode 1)

  					; visual move as standard move
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)
    )
#+END_SRC

And enable undo in non buffer files (?)

#+BEGIN_SRC emacs-lisp
  (use-package undo-tree
    :after evil
    :init
    (global-undo-tree-mode)
    (add-hook 'evil-local-mode-hook 'turn-on-undo-tree-mode)
    :config
    (unless (file-exists-p "~/.emacs.d/undo")
      (make-directory "~/.emacs.d/undo")
      )
    (setq undo-tree-history-directory-alist '(("." . "~/.emacs.d/undo")))
    )
#+END_SRC

Add some more evil keybindings.

#+BEGIN_SRC emacs-lisp
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+END_SRC

** general

Here are all keybinds starting with space

#+BEGIN_SRC emacs-lisp
  (use-package general
    :config
    (general-evil-setup t)

    (general-create-definer dtiderko/leader-keys
      :keymaps '(normal visual emacs)
      :prefix "SPC"
      )
    )
#+END_SRC

* M-x search

I dont really get this stuff but as far as i know everything under this chapter
serves to make M-x as usable as possible.

** ivy

#+BEGIN_SRC emacs-lisp
  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill)
           )
    :config
    (ivy-mode 1))
#+END_SRC

And an extension to show more information.

#+BEGIN_SRC emacs-lisp
  (use-package ivy-rich
    :init
    (ivy-rich-mode 1))
#+END_SRC

** counsel

#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :bind (("M-x" . counsel-M-x)
           ("C-x b" . counsel-ibuffer)
           ("C-x C-f" . counsel-find-file)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :config
    (setq ivy-initial-inputs-alist nil)
    (counsel-mode 1))
#+END_SRC

** prescient

Improve order of M-x entries.

#+BEGIN_SRC emacs-lisp
  (use-package ivy-prescient
    :after counsel
    :custom
    (ivy-prescient-enable-filtering nil)
    :config
    (prescient-persist-mode 1)
    (ivy-prescient-mode 1))
#+END_SRC

** helpful

Add helpful information to Emacs' describe- command buffers.

#+BEGIN_SRC emacs-lisp
  (use-package helpful
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))
#+END_SRC

* File management

** dirvish

#+BEGIN_SRC emacs-lisp
  (use-package dirvish
    :init
    (dirvish-override-dired-mode)
    :config
    (setq dired-listing-switches "-lX --almost-all --group-directories-first")
    (setq dirvish-attributes
          '(nerd-icons file-time file-size collapse subtree-state vc-state git-msg))
    (setq dirvish-mode-line-format
          '(:left (sort symlink) :right (omit yank index)))
    (setq dirvish-subtree-state-style 'nerd)
    (setq dirvish-default-layout nil)
    (setq dirvish-path-separators (list
                                   (format "  %s " (nerd-icons-codicon "nf-cod-home"))
                                   (format "  %s " (nerd-icons-codicon "nf-cod-root_folder"))
                                   (format " %s " (nerd-icons-faicon "nf-fa-angle_right"))))
    (setq delete-by-moving-to-trash t)
    )

  (dtiderko/leader-keys "pv" '(dirvish :which-key "Open dirvish"))
#+END_SRC

* Development environments

** projectile

Support for project management.

#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :init
    (setq projectile-project-search-path '(
					   ("~/" . 1)
					   ("~/coding/" . 2)
					   ("~/coding/uni/" . 2)
					   ))
    :config
    (setq projectile-enable-caching t)
    (global-set-key (kbd "C-c p") 'projectile-command-map)
    (projectile-mode +1)
    )

  (dtiderko/leader-keys
    "SPC" '(project-find-file :which-key "Find file in project")
    "g" '(projectile-ripgrep :which-key "Grep the project")
    )
#+END_SRC

And auto discover all available projects.

#+BEGIN_SRC emacs-lisp
(projectile-discover-projects-in-search-path)
#+END_SRC

Extension to intergrate with counsel.

#+BEGIN_SRC emacs-lisp
(use-package counsel-projectile
  :after projectile
  :config (counsel-projectile-mode))
#+END_SRC

** envrc

Enter devenv on project enter.

#+BEGIN_SRC emacs-lisp
(use-package envrc
  :hook (after-init . envrc-global-mode))
(with-eval-after-load 'envrc
  (define-key envrc-mode-map (kbd "C-c e") 'envrc-command-map))
#+END_SRC

** LSP

*** install missing modes

#+BEGIN_SRC emacs-lisp
(use-package cmake-mode)
(use-package css-mode)
(use-package haskell-mode)
(use-package json-mode)
(use-package js)
(use-package lua-mode)
(use-package markdown-mode)
(use-package nix-mode)
(use-package python-mode)
(use-package rust-mode)
(use-package sh-script)
(use-package yaml-mode)
(use-package zig-mode)
#+END_SRC

*** eglot

The main lsp thing starting servers and such.

#+BEGIN_SRC emacs-lisp
  (use-package eglot
    :ensure t
    :defer t
    :hook (
           (c-mode . eglot-ensure)
           (cmake-mode . eglot-ensure)
           (css-mode . eglot-ensure)
           (html-mode . eglot-ensure)
           (haskell-mode . eglot-ensure)
           (json-mode . eglot-ensure)
           (java-mode . eglot-ensure)
           (js-mode . eglot-ensure)
           (lua-mode . eglot-ensure)
           (markdown-mode . eglot-ensure)
           (nix-mode . eglot-ensure)
           (python-mode . eglot-ensure)
           (rust-mode . eglot-ensure)
           (sh-mode . eglot-ensure)
           (yaml-mode . eglot-ensure)
           (zig-mode . eglot-ensure)

           ; auto-format on save
    	   (after-save . dtiderko/eglot-format-or-external)
           )
    :config
    (add-to-list 'eglot-server-programs
                 '((rust-ts-mode rust-mode) .
                   ("rust-analyzer" :initializationOptions (:check (:command "clippy"))))

                 )
  )
#+END_SRC

And define the autoformat function

#+BEGIN_SRC emacs-lisp
    (defun dtiderko/eglot-format-or-external ()
      "Format buffer with LSP if available, else use custom formatters"
      (interactive)
      (if (and (bound-and-true-p eglot--managed-mode)
               (eglot-managed-p))
          (condition-case nil
              (eglot-format-buffer)
            (error (dtiderko/fallback-format)))
        (dtiderko/fallback-format)))

    (defun dtiderko/fallback-format ()
      "Fallback to external formatters for specific modes."
      (cond
       ((derived-mode-p 'python-mode)
        (dtiderko/python-format))
       ((derived-mode-p 'lua-mode)
        (dtiderko/lua-format))
       ))

    (defun dtiderko/python-format ()
      "Formatters for python"
      (when (buffer-file-name)
        (save-buffer)
        (shell-command (format "black --preview -q %s" (shell-quote-argument (buffer-file-name))))
        (shell-command (format "isort --profile black --float-to-top -q %s" (shell-quote-argument (buffer-file-name))))
        (shell-command (format "docformatter --in-place --black %s" (shell-quote-argument (buffer-file-name))))
        (revert-buffer t t t)
        ))

    (defun dtiderko/lua-format ()
      "Formatters for lua"
      (when (buffer-file-name)
        (save-buffer)
        (shell-command (format "stylua %s" (shell-quote-argument (buffer-file-name))))
        (revert-buffer t t t)
      ))
#+END_SRC

*** company

The pop up window showing stuff.

#+BEGIN_SRC emacs-lisp
  (use-package company
               :hook ((prog-mode . company-mode))
               :config
               (global-set-key (kbd "C-<SPC>") #'company-complete)
               :bind (:map company-active-map
                           ("<return>" . company-complete-selection)

                           ("<tab>" . company-select-next)
                           ("<backtab>" . company-select-previous)
                           )
               )
#+END_SRC

And an extension to show me documentation.

#+BEGIN_SRC emacs-lisp
(use-package company-quickhelp
  :after company
  :hook (company-mode . company-quickhelp-mode)
  :config
  (setq company-quickhelp-delay 0.2))
#+END_SRC

* Git

** Magit

Interface for git

#+BEGIN_SRC emacs-lisp
  (use-package magit)
  (dtiderko/leader-keys "G" '(magit-status :which-key "Open Magit"))
#+END_SRC

** Git Gutter

Actually good guide here: https://ianyepan.github.io/posts/emacs-git-gutter/

Show which lines are new/deleted/modified

#+BEGIN_SRC emacs-lisp
  (use-package git-gutter
    :hook (prog-mode . git-gutter-mode)
    :config
    (setq git-gutter:update-interval 0.02))
#+END_SRC

And modify the Bitmap for appearance

#+BEGIN_SRC emacs-lisp
  (use-package git-gutter-fringe
    :config
    (define-fringe-bitmap 'git-gutter-fr:added [224] nil nil '(center repeated))
    (define-fringe-bitmap 'git-gutter-fr:modified [224] nil nil '(center repeated))
    (define-fringe-bitmap 'git-gutter-fr:deleted [128 192 224 240] nil nil 'bottom)
    )
#+END_SRC

* Terminal

This terminal needs to compile a native library. Therefore, make sure to install all required libraries.

#+BEGIN_SRC emacs-lisp
  (use-package vterm
    :commands vterm
    :config
    (setq vterm-shell "bash")
  )
#+END_SRC

And add a keybind to open a new unique terminal.
  
#+BEGIN_SRC emacs-lisp
  (defun unique-vterm ()
    (interactive)
    (vterm)
    (rename-uniquely)
    )
  (dtiderko/leader-keys "t" '(unique-vterm :which-key "Open Terminal"))
#+END_SRC
