;; load the real config
;; this is the only line you really need to use config.org for configuration
(org-babel-load-file (concat user-emacs-directory "config.org"))

;; some autogenerated bullshit
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(all-the-icons-dired auto-package-update cmake-mode company-quickhelp
			 consult counsel-projectile dirvish
			 doom-modeline envrc evil-collection
			 evil-nerd-commenter general git-gutter-fringe
			 gruvbox-theme haskell-mode helpful
			 ivy-prescient ivy-rich json-mode lua-mode
			 magit marginalia markdown-mode nix-mode
			 orderless python-mode rainbow-delimiters
			 rust-mode session undo-tree vertico vterm
			 yaml-mode zig-mode))
 '(session-use-package t nil (session)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
